# Generated by Django 5.1.15 on 2026-07-01 14:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=8)),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Units of this currency per 1 USD.', max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
    ]
